spring:
  application:
    name: video
  datasource:
    url: jdbc:sqlite:./video.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8081

logging:
  level:
    root: INFO

app:
  auth:
    token-expire-hours: 12
    default-admin-username: admin
    default-admin-password: admin123
  zlm:
    base-url: ${APP_ZLM_BASE_URL:http://192.168.254.202:8080}
    secret: ${APP_ZLM_SECRET:ntModmVZiUw6arPbJiiuhfGC7FzNgWLx}
    public-base-url: ${APP_ZLM_PUBLIC_BASE_URL:http://192.168.254.202:8080}
    media-http-port: 8080
    default-app: rtp
  preview:
    allow-h265-direct-play: true
    enable-h265-transcode-fallback: false
  storage:
    cleanup-interval-seconds: 180
    cleanup-interval-ms: 180000
    zlm-record-path: ${APP_ZLM_RECORD_PATH:/record}
  gb28181:
    enabled: true
    auto-register-unknown-device: true
    local-ip: ${APP_GB28181_LOCAL_IP:192.168.254.202}
    local-bind-ip: ${APP_GB28181_LOCAL_BIND_IP:0.0.0.0}
    local-port: 5060
    media-ip: ${APP_GB28181_MEDIA_IP:192.168.254.202}
    server-id: 34020000002000000001
    domain: 3402000000
    user-agent: video-gb28181
    invite-timeout-ms: 8000
    ssrc-prefix: "0"
